### PR TITLE
PS account first alma activation

### PR DESCRIPTION
**Pull request by ClaireAlma**
### Reason for change

=
[Linear task](https://linear.app/almapay/issue/ECOM-1690/[%F0%9F%A7%A9-ps]-merchant-installing-the-module-for-the-first-time)

### How to test
When the alma module is already installed and configure, you see the connect PS link
If the alma module has no keys, you have not access to the alma form

### CODE REVIEW

**Review by joyet-simon — CHANGES_REQUESTED** [review]
The Alma form is opaque but we can still fill it, save and get the Alma configuration page.
image

**Comment by ClaireAlma** [comment]
@joyet-simon fixed

**Comment by ClaireAlma** [comment]
@joyet-simon I merge by error, can you test it on develop ? I'm sorry :/

**Review by joyet-simon — COMMENTED** [review]
Tests ok

**Pull request merged**
