### PR TITLE
[Security] Enable Aqua scanner on PR

### PR DESCRIPTION
**Pull request by remic-alma**
### Reason for change

Need to scan for vulnerabilities on code changes.

### Code changes

Add new workflow (`aqua.yml`) to trigger vulnerability scanner on PR.
Scanner in "audit mode" for now (non blocking).

### How to test

_As a reviewer, you are encouraged to test the PR locally._

### Checklist for authors and reviewers

- [ ] The title of the PR uses business wording, not technical jargon, for the changelog readers to understand it
- [ ] The PR implements the changes asked in the referenced task / issue
- [ ] The automated tests are compliant with the [testing strategy](https://www.notion.so/almapay/Backend-testing-strategy-06c642cec1bf47b9b8feca3a91ea8d4a)
- [ ] The tests are relevant, and cover the corner/error cases, not only the happy path
- [ ] You understand the impact of this PR on existing code/features
- [ ] The changes include adequate logging and Datadog traces
- [ ] Documentation is updated (API, developer documentation, ADR, Notion...)

### CODE REVIEW

**Comment by Benjamin-Freoua-Alma** [comment]
Hello @remic-alma 
Do you need any test in our side to approved this PR ?

**Comment by remic-alma** [comment]
> Hello @remic-alma Do you need any test in our side to approved this PR ?

No test needed.

**Comment by Benjamin-Freoua-Alma** [comment]
> > Hello @remic-alma Do you need any test in our side to approved this PR ?
> 
> No test needed.

Ok :) You need I approve this PR to make the merge ?

**Review by Benjamin-Freoua-Alma — APPROVED** [review]
Done :)

**Pull request merged**
